plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'application'
    id 'java'
    id 'maven-publish'
}

apply plugin: 'java'
apply plugin: 'com.github.johnrengelman.shadow'

group = project.group_id
version = project.version_name

publishing {
    publications {
        gpr(MavenPublication) {
            groupId = project.group_id
            artifactId = project.artifact_id
            version = project.version_name

            from components.java
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.25.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'
    implementation 'com.google.guava:guava:33.5.0-jre'
    implementation 'io.netty:netty-all:4.2.13.Final'
    implementation 'com.github.cao-awa:Cason:1.0.27'
    implementation 'com.github.cao-awa:CaperTML:1.0.0'

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

application {
    mainClass = 'com.github.cao.awa.kora.KoraEntryPoint'
}

shadowJar {
    archiveBaseName.set('Kora')
    archiveVersion.set(project.version_name)
    archiveClassifier.set('')
}

kotlin {
    jvmToolchain(24)
}

test {
    useJUnitPlatform()
}

sourceCompatibility = JavaVersion.VERSION_24
targetCompatibility = JavaVersion.VERSION_24